# Generated by Django 6.0.3 on 2026-04-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='repayment_power_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual monthly debt budget', max_digits=12, null=True),
        ),
    ]
