# Generated by Django 6.0.3 on 2026-04-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_repayment_power_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Mobile or contact number', max_length=15),
        ),
    ]
