# Generated by Django 6.0.3 on 2026-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='tenure_months',
            field=models.PositiveIntegerField(default=12, help_text='Planned repayment duration in months'),
        ),
    ]
