# Generated by Django 6.0.3 on 2026-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_debt_tenure_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='cleared_at',
            field=models.DateTimeField(blank=True, help_text='Date when debt was fully paid', null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
